### ISSUE TITLE
Feature Request: receive LLDP data from switch

### ISSUE THREAD

**Issue by jalons** [raspi/WinLLDPService#1]
I'd love to be able to receive LLDP information from a switch to identify from the system where it's connected without doing join logic on switch outputs. On our Linux hosts, we're able to do so with [lldpd](https://vincentbernat.github.io/lldpd/installation.html):

```
➜  sudo lldpctl -f keyvalue
lldp.eth0.via=LLDP
lldp.eth0.rid=1
lldp.eth0.age=16 days, 22:05:48
lldp.eth0.chassis.mac=xx:xx:xx:xx:xx:xx
lldp.eth0.chassis.name=switchhostname.domain.tld
lldp.eth0.chassis.descr=Arista Networks EOS version 4.13.7.2M running on an Arista Networks DCS-7148S
lldp.eth0.chassis.mgmt-ip=XXX.XXX.XXX.XXX
lldp.eth0.chassis.Bridge.enabled=on
lldp.eth0.chassis.Router.enabled=on
lldp.eth0.port.ifname=Ethernet38
lldp.eth0.port.mfs=9236
lldp.eth0.vlan.vlan-id=XXX
lldp.eth0.vlan.pvid=yes
```

**Comment by raspi** [comment]
Thanks for the FR. Unfortunately this project's scope and goal is only to send LLDP packets to switch(es). I might take a look into this as an another project in the future.
