### ISSUE TITLE
Automatic Deployment using GPO

### ISSUE THREAD

**Issue by SnakeNET256** [raspi/WinLLDPService#13]
Request for enhancement : GPO Deployment

The installer try to open a web browser to reach a website. that give a warning on my end-user laptop. Quite annoying. and not usable in a domain-wide environment. 

Could you detect the installation is triggered by GPO and then avoid this webpage openning?
It's laucnhed by user "System" if that can help.

Tested on : 
Windows 7 Ultimate 64 bit
Is machine connected to Active Directory?  Yes
Specify what Windows version is running AD : 2012R2
Specify if you're using [Samba](https://www.samba.org/) as AD: No
Version the issue has been seen with : 17.2 (64bit)

**Comment by raspi** [comment]
Have you tried running the installer in quiet mode?

**Comment by lucize** [comment]
I have it installed without issues on windows 7 x64, no webpage, v17.07.23.2312, default gpo package install on win2008r2 but it fails on windows 10 with some .net error

```

Application: WinLLDPService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WinLLDPService.OsInfo.GetServiceTag()
   at WinLLDPService.OsInfo.GetStaticInfo()
   at WinLLDPService.WinLLDPService.InitializeComponent()
   at WinLLDPService.ServiceMain.Main()

---
Faulting application name: WinLLDPService.exe, version: 17.7.23.2312, time stamp: 0x5975039b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff8d4330c15
Faulting process id: 0xad0
Faulting application start time: 0x01d304225840bb89
Faulting application path: C:\Program Files\WinLLDPService\WinLLDPService.exe
Faulting module path: unknown
Report Id: cd5bbd82-1fd4-4a65-aa5e-06588efa3f81
Faulting package full name: 
Faulting package-relative application ID: 

```

**Comment by lucize** [comment]
spoke too soon, on some devices the web browser is starting, the gpo policy ads by default /q

**Comment by raspi** [comment]
The chocolatey install uses [these arguments](https://github.com/raspi/WinLLDPService/blob/master/WinLLDPService/build/chocolatey/template/tools/chocolateyinstall.ps1#L19).

**Comment by raspi** [comment]
Web page is no longer opened.

https://github.com/raspi/WinLLDPService/releases/tag/v17.10.20.2236
