### ISSUE TITLE
Webpage Open on Install

### ISSUE THREAD

**Issue by Ethanb00** [raspi/WinLLDPService#14]
### Submission type
  - Request for enhancement
### Used version of operating system

> Windows 10 Enterprise LTSB

### Request
I am working to do a silent install with chocolatey for my organization. Everything looks great, and I truly appreciate the product.  However, when I do a silent install through the msi or choco (which works), the install concludes by opening [this page](https://raspi.github.io/projects/winlldpservice/install/?ver=17.02.15.2317).  Is there a way to disable this feature for deployment so that it is truly silent. I totally get that you want folks to know that you created this service, but it would probably freak out my users. 

Thanks for your time.

**Comment by raspi** [comment]
Web page is no longer opened.

https://github.com/raspi/WinLLDPService/releases/tag/v17.10.20.2236
