### ISSUE TITLE
Hidden device created by Npcap doesn't support promiscuous mode

### ISSUE THREAD

**Issue by sepo** [raspi/WinLLDPService#16]
### Submission type

- [x] Bug report
- [ ] Request for enhancement

### Used version of operating system

Windows 7 Pro 64 bit

### In case of bug report: Is machine connected to Active Directory?

- [x] Yes (domain functional level is 2008 R2)

### Version the issue has been seen with

v17.10.20.2236 64 bit

### Expected behavior i didn't see

- Switch receives LLDP information
- LLDP packets in wireshark monitoring the ethernet interface

### Unexpected behaviour i saw

- Warning in the eventlog (see below)
  - But i think this is not the problem since it is only a warning

### Steps to reproduce the problem 

There are no specific steps. This is the behavior since the installation.

### Additional details

- I can see the LLDP paket from the switch

- npcap version
v0.97

- Switch details
   - Cisco SG200-50
   - Firmware 1.4.0.88
   - LLDP works. I can see other devices.

- Eventlog warning
  - Note: {78032B7E-4968-42D3-9F37-287EA86C0AAA} is not my ethernet card.
```
Packet sent failed: SharpPcap.PcapException: Unable to open the adapter (rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}). rpcap://\Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}: failed to set hardware filter to promiscuous mode
   bei SharpPcap.LibPcap.LibPcapLiveDevice.Open(DeviceMode mode, Int32 read_timeout)
   bei WinLLDPService.WinLLDP.OpenDevices(List`1 adapters)
   bei WinLLDPService.WinLLDP.Run()
   bei WinLLDPService.WinLLDPService.SendPacket(Object source, ElapsedEventArgs ea) 
```

- No non-ASCII characters in network interface or computer name.
  - Network interface name: LAN-Verbindung
  - Computername: PCI56123

- .NET framework version
v4.6.1

- MSI installer version
v5.0.7601.23593

- Did you try to update msiexec and/or .NET framework?
No

- Did you try also the 32 bit installer on 64 bit system?
Yes

- Did you try on different machine(s)?
Yes

**Comment by raspi** [comment]
Could you provide the output of:

    Get-NetAdapter | select *

And:

    Get-WmiObject -Class Win32_NetworkAdapter | select *

These list details about network adapters in PowerShell.

**Comment by sepo** [comment]
The cmdlet `Get-NetAdapter` is not available on Windows 7.

Here is the output of `Get-WmiObject -Class Win32_NetworkAdapter | select *`.
[Win32_NetworkAdapter.txt](https://github.com/raspi/WinLLDPService/files/1520869/Win32_NetworkAdapter.txt)

**Comment by sepo** [comment]
I've removed npcap and installed winpcap v4.1.3 instead and now it works. Win10Pcap works also.

**Comment by raspi** [comment]
Ok. That `{78032B7E-4968-42D3-9F37-287EA86C0AAA}` must be then some kind of hidden adapter created by npcap which doesn't allow promiscuous mode. I'm currently investigating with Windows 7 Pro VM image from MS but can't replicate the bug yet.

**Comment by raspi** [comment]
Could you still try only with npcap? There's [Npcap bug report instructions](https://github.com/nmap/npcap#bug-report). And from there:

* Diagnostic report
* General installation log
* Driver installation log

These would help me to find the bug. Thanks.

**Comment by raspi** [comment]
https://github.com/raspi/WinLLDPService/releases/tag/v18.02.04.2335 Open a new issue if problem still exists.
