### ISSUE TITLE
Too much data exposed 

### ISSUE THREAD

**Issue by Voljka1** [raspi/WinLLDPService#17]
### Submission type

  - [x ] Request for enhancement

### Used version of operating system
>Windows 10 Enterprise Fall Creator update x64

Hello. Please provide some control over what information are exposed via LLDP. 
I see a lot of data going from PC to switch, and when PC are not in domain network this can be security risk. May be you can add some registry key for 1) Send only hostname, 2) Hostname+IP address as a minimum enhancement.

**Comment by raspi** [comment]
https://github.com/raspi/WinLLDPService/releases/tag/v18.02.04.2335
