### ISSUE TITLE
Investigate: Bundle WinPcap DLL to installer

### ISSUE THREAD

**Issue by raspi** [raspi/WinLLDPService#2]
See if it's possible to just bundle WinPcap DLL directly to .msi installer via WiX builder. Possible problems: no admin rights to install. Have to investigate WiX UAC/admin privilege docs too.

**Comment by raspi** [comment]
Check also http://www.win10pcap.org/

**Comment by hsluoyz** [comment]
Hi, @raspi,

Please try Npcap: https://github.com/nmap/npcap

Npcap is a fork of WinPcap updated for NDIS 6. You can bundle the DLLs, but **the driver always needs to be installed with Administrator**.

**Comment by raspi** [comment]
https://github.com/chmorgan/sharppcap/commit/62df7a39b90c45f448e7dea7d6f93e6cfda72247

**Comment by SnakeNET256** [comment]
I'm currently deploying WinLLDPSErvice using GPO so admin rights are not a problem.
I will test to deploy NPCAP silently too.

Keep you informed.

**Comment by raspi** [comment]
v17.10.20.2236 now supports whatever SharpPCap supports (winpcap, npcap, ..).

**Comment by lucize** [comment]
so do we have to install SharpPCap or the libs are provided in the build ?
thank you !

**Comment by raspi** [comment]
SharpPcap is bundled in the installer (and always been). You must manually install winpcap or npcap or other capture library supported by SharpPCap. 

Older installer checked for winpcap and that check is now **removed**. 

So now if you install WinLLDPService you've have to install some capture library first. Otherwise WinLLDPService installer will fail or there's ton of missing DLL errors in the Event Viewer.

**Comment by raspi** [comment]
Conclusion: Users can choose what capture library to use (what sharppcap supports) and installer doesn't check for any capture library installations.
