### ISSUE TITLE
Is it possible to create WinLLDPService Portable Version for WinPE?

### ISSUE THREAD

**Issue by Sharkrit** [raspi/WinLLDPService#24]
I want to create PXE boot for bare metal machine with WinPE x64. Is it possible to run these binary in WinPE x64 mode?

**Comment by raspi** [comment]
As per https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro : 

> Windows PE does not support any of the following:
> * .MSI installation files.

So no.
