### ISSUE TITLE
Co-Existence with Microsofts-LLDP-Driver (Service: MSLLDP)

### ISSUE THREAD

**Issue by gunnarhaslinger** [raspi/WinLLDPService#28]
May I ask how Co-Existence with Microsofts-LLDP-Driver should be handled?

Current Win10-Releases have Service "MsLldp" running. It sends some LLDP Packets immediately after Ethernet-Cable gets plugged in, checked with wireshark.

When Installing WinLLDPService I can see both, LLDP Pakets from MSLLDP and from WinLLDPService. The Microsoft-sent Packets just contain Chassis Subtype and Port Subtype as MAC-Address and MAC/PHY Config/Status. WinLLDPService provides much more Information.

Should MSLLDP Service be turned off and Binding to the NICs removed?
Is there any Idea how to configure MSLLDP Service? For example to send additional Fields or just modify the existing ones?

**Comment by raspi** [comment]
WinLLDPService was developed before Microsoft's LLDP driver even existed so I'd say disabling it is ok.

**Comment by gunnarhaslinger** [comment]
Disabling MSLLDP could be done by:
`sc config MSLLDP start= disabled`

Hint: Space between "=" and "disabled" is intentional!
