### ISSUE TITLE
Unable to start the WinLLDPService

### ISSUE THREAD

**Issue by joel-bryant** [raspi/WinLLDPService#9]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement

*NOTE: Do not submit anything other than bug reports or enhancements via the issue tracker!*

*NOTE: Only submit one enhancement or bug per issue!*

### Version the issue has been seen with

>16.12.22.1802

*NOTE: Do not submit bug reports about anything but the two most recently released versions!*

### Used version of operating system
For example: Windows 7 Ultimate 64 bit

>Windows 7 Pro 64 bit

### Is machine connected to Active Directory?

 - [X ] Yes

Also specify if you're using Samba as AD.
 
### In case of bug report: Expected behaviour you didn't see

>I expected to start service and verify lldp functionality, but instead it could not start the service

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

>Fresh install, interrupted because could not start service

**Comment by raspi** [comment]
Please provide install log. Run as admin.

This can be done via running:

    msiexec /i "installer.msi" /L*V "install.log"

See `msiexec /?` for help.

**Comment by joel-bryant** [comment]
Joel Bryant

joel.dean.bryant@gmail.com

(704) 600-5441

**Comment by raspi** [comment]
If you tried to send attachment via email GitHub ignores them. Use GitHub issue tracker to send files.

**Comment by joel-bryant** [comment]
[install.txt](https://github.com/raspi/WinLLDPService/files/719737/install.txt)

**Comment by raspi** [comment]
There seems to have no permission(s) to install services. 

> Error 1920. Service 'WinLLDPService' (WinLLDPService) failed to start. Verify that you have sufficient privileges to start system services.
> MSI (s) (58:FC) [15:02:57:996]: Product: WinLLDPService -- Error 1920. Service 'WinLLDPService' (WinLLDPService) failed to start. Verify that you have sufficient privileges to start system services.
> 

Instructions:

https://support.microsoft.com/fi-fi/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation-error-message-when-you-try-to-install-a-windows-installer-package

**Comment by raspi** [comment]
Closing because it's OS (permission(s)) related.
